# Generated by Django 6.0.7 on 2026-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
                ('gelesen', models.BooleanField(default=False, verbose_name='Gelesen')),
            ],
            options={
                'verbose_name': 'Kontaktnachricht',
                'verbose_name_plural': 'Kontaktnachrichten',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='FrequencyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=120, verbose_name='Ort')),
                ('frequenz', models.CharField(help_text='z. B. "98.5", "Kanal 9C" oder "App & Web"', max_length=60, verbose_name='Frequenz / Kanal')),
                ('empfangsart', models.CharField(max_length=120, verbose_name='Empfangsart')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Empfangsweg',
                'verbose_name_plural': 'Empfangswege',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=120, verbose_name='Titel')),
                ('zeitraum', models.CharField(help_text='z. B. "06:00 – 10:00" oder "Wochenende"', max_length=60, verbose_name='Uhrzeit')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('reihenfolge', models.PositiveIntegerField(default=0, help_text='Kleinere Zahl = weiter oben in der Liste', verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Sendung',
                'verbose_name_plural': 'Sendungen',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
    ]
